/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IMVPIoTProcessor  {
    function submitResult(bytes32 task_id, uint8[] memory encrypted_result, bytes32 proof_hash) external;

    function getResult(bytes32 task_id) external view returns (uint8[] memory, bytes32, uint256, address);
}
